# Change these first
owner: fintatica # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Website
    url: https://fintatica.com.br
  - name: API
    url: https://api.fintatica.com.br/v1/health?api_key=$API_KEY

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fintatica.com.br
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Fintatica Status Page
  introTitle: "**Fintatica** is turning messy Brazilian market data (CVM/B3/IBGE etc.) into clean, developer-first APIs and bite-size insights."
  introMessage: See, we always reach our SLA!
  navbar:
    - title: GitHub
      href: https://github.com/fintatica
    - title: Website
      href: https://fintatica.com.br
